### ISSUE TITLE
merlin dose not run

### ISSUE THREAD

**Issue by k1197445** [Roy-lab/merlin-p#1]
I am using Ubuntu 16.04. type ./merlin shows following message:
./merlin: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory

**Comment by asiahpirani** [comment]
Thank you for reporting this issue.

We have included the shared library files under gsl_lib/ directory. If you add the path to this directory to your LD_LIBRARY_PATH environmental variable, you should be able to run MERLIN.

If it doesn't work, you should be able to install libgsl using the package manager in Ubuntu. Try:
$ sudo apt-get install libgsl-dev
After installing the library, you can remove the "-L$(LIBPATH)" from the Makefile and compile the program again.

**Comment by k1197445** [comment]
Solved. Thank you.
